### ISSUE TITLE
provided-mode-derived-p ?

### ISSUE THREAD

**Issue by avkoval** [Alexander-Miller/treemacs#32]
* version 1.8.5 installed from melpa
* pressing TAB on some files 2 problems:
  - imenu-unavailable-error: imenu unavailable: "This buffer cannot use ‘imenu-default-create-index-function’"
  - treemacs--post-process-index: Symbol’s function definition is void: provided-mode-derived-p

**Comment by avkoval** [comment]
After this:
5573341 * Add basic tags post process to decide top level leaf section name.

**Comment by Alexander-Miller** [comment]
> version 1.8.5 installed from melpa

Technically it's 1.8.6, I mistyped in magit, so the version bump wasn't in when I pushed.

> Symbol’s function definition is void: provided-mode-derived-p

Looks like I picked a function that was introduced only very recently - I've 2 laptops where I compile emacs myself and it's only available on one of them. Fix should be pushed today.

> imenu-unavailable-error: imenu unavailable: "This buffer cannot use ‘imenu-default-create-index-function’"

Not sure what to make of that. Can you give an example of a buffer where that happens? Does default imenu still work there?

**Comment by bmag** [comment]
Regarding `provided-mode-derived-p`, @Alexander-Miller  it looks like https://github.com/Alexander-Miller/treemacs/commit/79fc814888923835370dfad7938457c3d0620388 was supposed to fix it, but you forgot to change `treemacs--post-process-index` to use `treemacs--provided-mode-derived-p`, so the bug is still there.

**Comment by Alexander-Miller** [comment]
🤦‍
 I'll fix this later today.

**Comment by avkoval** [comment]
Looks like fixed. Thank you, Alexander!
