### ISSUE TITLE
Treemacs is not loading when dotspacemacs-auto-resume-layouts is set to true

### ISSUE THREAD

**Issue by davidelbaze** [Alexander-Miller/treemacs#40]
On spacemacs, there is a functionnality which able to resume layout when starting emacs.

If I have a layout with treemacs nav, and a source code open in the buffer, if I close and reopen emacs, my source code buffer is there, but instead of having a treemacs buffer on the left, I have a empty Text one.

**Comment by Alexander-Miller** [comment]
Pushed a patch. Let me know if it works for you.

**Comment by davidelbaze** [comment]
Hi, 

doesn't seems to work.. I still have "Replaced deleted *Treemacs* buffer with *scratch*" message.

Any idea ?

**Comment by Alexander-Miller** [comment]
When I said I pushed a patch I meant literally just now. MELPA meanwhile takes about 4 hours to complete a build. So you just have to wait a bit.

You'll know you've downloaded the new version when the value of `treemacs-version` is at least 1.9.2.

**Comment by davidelbaze** [comment]
It is, I applied your patch locally.
Maybe the cache was not cleaned.

**Comment by davidelbaze** [comment]
It was the cache ! I didn't removed the .elc file.
It's now working perfectly ! Thanks !

**Comment by idanov** [comment]
This still happens to me, using latest Spacemacs and Treemacs v3.1. The Treemacs buffer gets replaced with the scratch buffer on emacs restart with reloaded layouts. The message I get in the message buffer is:
```
Replaced deleted  *Treemacs-Scoped-Buffer-Perspective ~/workspace/project/* buffer with *scratch*
```

**Comment by Alexander-Miller** [comment]
I haven't used spacemacs in a very long time. To help with this I'll need to know which package it uses for its layout storage.
