### ISSUE TITLE
Treemacs can be other-window

### ISSUE THREAD

**Issue by ambihelical** [Alexander-Miller/treemacs#47]
Currently treemacs' window can be other-window, which means sometimes it will be used by some packages which need to show another buffer (e.g. magit).  Since  treemacs is usually tall and narrow, this is basically useless in most cases.  As an example, if magit has unmerged commits showing in its status window, hitting return on one of these will use the other-window if it exists, to display it.  When this is treemacs, the result is not very nice.  

Would it possible to set treemacs's window with the 'no-other-window parameter to prevent this from happening?  I've experimented with this a little, and it seems to be an improvement, although the flag isn't as persistent as I would like (can get reset, but I'm not sure of the conditions yet), so probably some more work is involved.

**Comment by Alexander-Miller** [comment]
I cannot reproduce this, even without shackle, but your solution should be viable. Try out this:

```
(defun treemacs--set-not-other-window ()
  (-when-let (w (treemacs--is-visible?))
    (set-window-parameter w 'no-other-window t)))
(add-hook 'window-configuration-change-hook #'treemacs--set-not-other-window)
```
This ought to always keep the parameter around (maybe outside of right after frame creation). If it works for you I'll write a proper patch.

**Comment by ambihelical** [comment]
The basic idea works at least as far as setting no-other-window. Unfortunately it doesn't completely solve the ultimate issue for me.  Basically magit will still split treemacs window, at least on a machine with enough vertical space to split.  My initial experiments were on a screen with less vertical space then needed, so it seemed like a solution because it fell back to using the magit status buffer's window.  However on another machine with a much larger monitor, it sill splits treemacs window, which isn't desirable, imo.  I think I may have not done enough due diligence on it.   I will look at it some more later.

**Comment by Alexander-Miller** [comment]
I'm not sure this kind of compatibility work is even viable. The deep interference with emacs' window management needed to keep things straight here is best served by a package dedicated to that purpose. I recommend you try shackle. It's fairly easy to set up a couple of rules that just show a commit window always on a specific side/the same window. You can also just specify a custom function.

It's also probably not a good idea to keep treemacs around magit. Other than you current issues follow-mode might drag you to places like .git/COMMIT_EDITMSG (a fix is on my radar, but I'm currently busy with the slow march towards frame-locality). Even on my large 1440p screen at work I prefer to start magit in fullscreen.

**Comment by ambihelical** [comment]
All of the problems I've been having (unintended splitting, acting as other-window, resizing possibly, and maybe even shell-pop) seem to stem from the move away from side window.  Were the problems with that implementation that bad?  I only know about the other guy's shell-pop issue (which it looked like he found a fix for), but I guess there were other difficulties.  Lacking an epic move back to side window, I'll probably be looking at automatically closing the treemacs window when magit is active.  This doesn't sound too bad if it is possible.  If not I'll look at shackle.

**Comment by Alexander-Miller** [comment]
There's no real winner here, but side window literally breaks other packages, so not using it is the lesser evil.

> I'll probably be looking at automatically closing the treemacs window when magit is active

Spacemacs has a config var for it. Here's what it does:
`(setq magit-display-buffer-function 'magit-display-buffer-fullframe-status-v1)`

>  If not I'll look at shackle

Just remembered you posting your popwin config. Popwin and shackle should be mostly equal w.r.t their window management ability. Only difference I know is that I haven't found a fullscreen option in popwin, but magit offers that on its own anyway.

There's also something called window-purpose that looks like a brand-new and interesting way to manage windows, but I haven't really tried it yet.

**Comment by ambihelical** [comment]
Thanks for your suggestions, but I'd rather leave the window configuration alone when I run magit, as I sometimes have 4-6 windows in view.  I am trying out setting split-window-preferred-function to a
function which does not allow splitting of 'not-other-window, but otherwise just calls split-window-sensibly, combined with something like the window configuration hook you provided. If it doesn't break anything, problem should be solved, for me anyway. So far so good. 

Could you possibly list the packages that can't handle a side window, I'm curious to see if my hack also breaks them.

**Comment by Alexander-Miller** [comment]
The only one I know of so far is shell-pop. That's not much, but there's bound to be more, and if I join spacemacs I'll be breaking another layer. Of course the potential for the kind of workflow breakage you experience doesn't sit well with me either. 

Fuck it, I'll make a minor mode for it, slap on a bunch of warnings, and we'll have the lessest possible evil. Shouldn't be too much work either,  ETA is over the weekend.

**Comment by Alexander-Miller** [comment]
Other-window fix is now on master. See the new `treemacs-is-never-other-window` option.

**Comment by ambihelical** [comment]
Thanks!  One problem with it - the flag is not initially set after running treemacs-projectile or the first time treemacs-toggle is invoked.  After I split a window, the flag is set, so the configuration hook is working fine.

**Comment by Alexander-Miller** [comment]
Ah, I didn't test things with a cold start - it's not set at first because the hook is only added after treemacs first changes the window config.

Fix is pushed now.

**Comment by ambihelical** [comment]
I'm seeing some interaction with this option and perspectives.  Basically the 'no-other-window parameter is being found on windows it shouldn't be set in a newly shown perspective. I believe this to be true because the other-window command won't go to these windows. 

I put a (message) in treemacs--on-window-config-change, and it seems the set-window-parameter code is being executed even when treemacs window is not actually visible.  I haven't debugged this very deeply however, I'm not sure how to correlate window names to actual windows. 

To reproduce:
1. Open two perspectives with two windows each from different projectile projects.  Use other-window to navigate between the windows in each perspective, showing everything is normal.  I used projects with disjoint trees and split the window of a single buffer for each.  The projectile part may not be necessary, but that's what I did. 
2. In one perspective, open treemacs and close it.  I use treemacs-toggle for this.
3. Switch between the two perspectives a few times. 
4. Try other-window in each perspective to see that at least one window has no-other-window set because other-window will not navigate to it.  You can do this during (3) as well, but it seems to take a few switches before the problem occurs.

**Comment by Alexander-Miller** [comment]
I'm afraid I can't reproduce this, though I'll try some more tomorrow. In the meantime try this, see if it gives you anything useful:
```
(defun treemacs--on-window-config-change ()
  "Collects all tasks that need to run on a window config change."
  (message "DEBUG: On window change for windows %s" (window-list))
  (-when-let (w (treemacs--is-visible?))
    (message "DEBUG: Found treemacs window %s showing buffer %s" w (window-buffer w))
    (with-selected-window w
      (message "DEBUG: Running hook with selected window %s" (selected-window))
      ;; Reset the treemacs window width to its default - required after window deletions
      (when treemacs--width-is-locked
        (treemacs--set-width treemacs-width))
      ;; Prevent treemacs from being used as other-window
      (when treemacs-is-never-other-window
        (set-window-parameter w 'no-other-window t)
        (message "DEBUG: Set no-other-window of %s to %s" (selected-window) (window-parameter (selected-window) 'no-other-window)))))
  (message "DEBUG: Finish hook"))
```

**Comment by ambihelical** [comment]
It seems to only be setting the flag on *Treemacs* buffer window, even though I still see other-window not allowing navigation as expected.  Also it seems to be doing so even though treemacs is not visible.  I'm somewhat baffled by these results.  I only had treemacs visible once, by the way.  I'm not sure how its window changed?
```
View mode: type C-h for help, C-h m for commands, q to quit.
DEBUG: On window change for windows (#<window 10 on *Treemacs*> #<window 3 on init.el> #<window 6 on init.el>)
DEBUG: Found treemacs window #<window 10 on *Treemacs*> showing buffer *Treemacs*
DEBUG: Running hook with selected window #<window 10 on *Treemacs*>
DEBUG: Set no-other-window of #<window 10 on *Treemacs*> to t
DEBUG: Finish hook
DEBUG: On window change for windows (#<window 3 on init.el> #<window 6 on init.el>)
DEBUG: Finish hook
DEBUG: On window change for windows (#<window 3 on *scratch* (rtags-master)> #<window 6 on init.el>)
DEBUG: Finish hook
DEBUG: On window change for windows (#<window 3 on AST.cpp> #<window 6 on init.el>)
DEBUG: Finish hook
DEBUG: On window change for windows (#<window 3 on AST.cpp> #<window 8 on AST.cpp>)
DEBUG: Finish hook
DEBUG: On window change for windows (#<window 3 on  *Echo Area 1*> #<window 8 on AST.cpp>)
DEBUG: Finish hook
DEBUG: On window change for windows (#<window 3 on  *Echo Area 0*> #<window 8 on AST.cpp>)
DEBUG: Finish hook
DEBUG: On window change for windows (#<window 3 on  *code-conversion-work*> #<window 8 on AST.cpp>)
DEBUG: Finish hook
DEBUG: On window change for windows (#<window 3 on *Messages*> #<window 8 on AST.cpp>)
DEBUG: Finish hook
DEBUG: On window change for windows (#<window 3 on  *Minibuf-0*> #<window 8 on AST.cpp>)
DEBUG: Finish hook
DEBUG: On window change for windows (#<window 3 on *scratch*> #<window 8 on AST.cpp>)
DEBUG: Finish hook
DEBUG: On window change for windows (#<window 3 on init.el> #<window 8 on AST.cpp>)
DEBUG: Finish hook
DEBUG: On window change for windows (#<window 3 on *Treemacs*> #<window 8 on AST.cpp>)
DEBUG: Found treemacs window #<window 3 on *Treemacs*> showing buffer *Treemacs*
DEBUG: Running hook with selected window #<window 3 on *Treemacs*>
DEBUG: Set no-other-window of #<window 3 on *Treemacs*> to t
DEBUG: Finish hook
DEBUG: On window change for windows (#<window 3 on init.el> #<window 6 on init.el>)
DEBUG: Finish hook
DEBUG: On window change for windows (#<window 4 on  *Minibuf-1*> #<window 3 on init.el> #<window 6 on init.el>)
DEBUG: Finish hook
DEBUG: On window change for windows (#<window 6 on init.el> #<window 3 on init.el>)
DEBUG: Finish hook
DEBUG: On window change for windows (#<window 6 on *Messages*> #<window 3 on init.el>)
DEBUG: Finish hook
```

**Comment by ambihelical** [comment]
Side windows branch looks good.  I turned off never-side-window and turned on the side window option.  Some observations:
1. shell-pop works with treemacs showing as long as shell-pop-full-span is nil (the default).  Otherwise it doesn't work at all. You can't run shell-pop from treemacs window at all.  Neither of these things bother me much.
2. Magit works well with this config.  There is no need for never-side-window with this on. 
2. No  other problems so far.  I'll use this configuration at work this week and get back to you if there are any issues.

**Comment by Alexander-Miller** [comment]
> Also it seems to be doing so even though treemacs is not visible. I'm somewhat baffled by these results. I only had treemacs visible once, by the way. I'm not sure how its window changed?

Is the hook being run at all that's surprising you? If so, there's nothing wrong here. The hook is globally set, *any* window config change will all least try to look for a treemacs window. I never even consideren making it buffer-local, it just seemed natural, that a hook that runs on a window config change, means the *entire* window config, or at least the windows of the current frame. 
I tried making the hook local to the treemacs buffer and so far it seems to work just right. I've pushed that change to the other-window branch now, maybe it'll help with persp.

**Comment by ambihelical** [comment]
No, the part that confuses me is the fact that the no-other-window part is executing even though treemacs is not visible.   The first setting on window 10 makes sense, probably when it first appeared, but I ran treemacs-toggle in quick succession.  Why is there another setting later on window 3?

**Comment by Alexander-Miller** [comment]
Random guess: something somewhere is not quite deterministic (or something changed through the constant switches) such that the treemacs window was visible for an instant, during some window-splitting, buffer-switching process.

See if making the hook local helps (It's not called when creating frames, I'll need to fix that).

**Comment by ambihelical** [comment]
I tried the updated side-window branch.  With treemacs-is-never-other-window, the behavior is the same. 
With treemacs-persistant-side-window, I got different but wrong behaviour which can be reproduced as follows:

1. Set up 2 perspectives, with a split window on each. 
2. In one of these, open and close treemacs.
3. Switch to other perspective.  Open and close treemacs. 
4. Switch back to perspective of #2.  Open treemacs will give "cannot split side window or parent of side window" even though there is no side window visible. 

For "open and close treemacs" I used both treemacs-toggle and treemacs-projectile, followed by "q".  Both methods have this behaviour.

**Comment by Alexander-Miller** [comment]
> Currently treemacs' window can be other-window, which means sometimes it will be used by some packages which need to show another buffer

Looking back at your first comment this should not be happening since the treemacs window is strongly dedicated to its buffer. Maybe thats the root of the issues your having, so lets give testing that dedication a try. You can use this function:
```
(defun test-treemacs-dedication ()
  (interactive)
  (-if-let (w (treemacs--is-visible?))
      (treemacs--log "Window is dedicated: %s" (window-dedicated-p w))
    (treemacs--log "No window")))
(global-set-key (kbd "C-x M-l") #'test-treemacs-dedication)
```
If you ever see this output a nil well have found ourselves a bug.

**Comment by ambihelical** [comment]
For this I turned off persistant-side-window and is-never-other-window.  FYI, I also had to rebase side-window branch on master due to some problem with pfuture. It always seems to be dedicated when I run the above command.  Sorry, but I think my initial comment may have been a little off and caused this whole issue to drift.  Basically what I (currently) see is that the treemacs window can be split and the bottom half used to show a magit buffer, which sucked because it's too narrow.  I'm not sure I ever saw treemacs window being completely used for something else, although if it does I'll be sure to open a bug report.  The side window option prevents the splitting, but there are still some issues with it.  Maybe we can track that in another issue and close this one.

**Comment by Alexander-Miller** [comment]
Just to be clear, which perspective are we talking about - [persp-mode.el](https://github.com/Bad-ptr/persp-mode.el) or [perspective-el](https://github.com/nex3/perspective-el)?

I am using persp-mode, its the one that comes with spacemacs.
I also just updated the side-window brach with all the newest changes, features mostly, so nothing should change here. The bit about pfuture is a breaking change on the side of treemacs that allows using pfuture in emacs24.

I installed emacs25 from the official repos and tried your recipe again, still no success. Assuming were using the same perspective package I think its time to dig into your config. Do you still see the same behaviour when you start from emacs -q and load nothing but must-haves like treemacs, magit and persp?

**Comment by ambihelical** [comment]
I am indeed using perspective-el. I didn't know there was more than one.

**Comment by ambihelical** [comment]
Also, if it matters I am using projectile-persp as well.

**Comment by Alexander-Miller** [comment]
Maybe a change is in order? I dont know how perspective-el works, but judging from the bugs you experience I would probably need to dig quite deeply - for a package that hasnt seen activity in a year and has a the-same-but-more-features successor.
I'd honestly rather concentrate on new features, like extending follow mode to tags, than chasing such difficult-to-track bugs.

For what its worth spacemacs has a layouts layer that, among other things, integrates projectile with persp. You could use that.

**Comment by ambihelical** [comment]
I don't know if the spacemacs layer will do me any good, but I'll try the other package.

**Comment by Alexander-Miller** [comment]
Not the whole layer, but there are parts that e.g. allow to select a perspective for a project, which sounds like a replacement for projectile-persp.

**Comment by ambihelical** [comment]
Oh right.  I totally failed at getting that package working, just like the first time I tried it when I started with emacs a few years ago.  Sorry that I didn't update here, I worked at it back when you suggested it.  I don't remember the details of the problems.

**Comment by Alexander-Miller** [comment]
I'll be closing this then. The issues you are having are caused by perspective, not treemacs. The treemacs window is strongly dedicated to showing only the treemacs buffer. For me it is impossible to make the treemacs window show any other buffer. If some other package manages to do just that on your end it's probably caused by that window dedication getting lost somehow. I assume perspective is using some faulty approach to manage windows, since both eyebrowse and persp work without problems.

For your problems with persp I suggest seeing if it's doing what you want in spacemacs, and if yes try and get the spacemacs code into your own config.
