### ISSUE TITLE
Update projectile-projects-cache after creation of file using treemacs-create-file

### ISSUE THREAD

**Issue by nixmaniack** [Alexander-Miller/treemacs#595]
When a file or dir is created using `treemacs-create-file` (keybinding: `cf`), the newly created file is not added to `projectile-projects-cache`. This prevents opening files using `projectile-find-file`.

Newly created files using `find-file` are automatically added. Projectile facilitates this using `projectile-find-file-hook-function` which is added to `find-file-hook`. 

Similar provision in `treemacs-projectile` integration would be helpful. 

Current workaround is to invalidate the cache `projectile-invalidate-cache` or pass universal arg to `projectile-find-file` which automatically invalidates the cache.

**Comment by Alexander-Miller** [comment]
Sounds good to me.

**Comment by Alexander-Miller** [comment]
Should work now. You will need to update both treemacs and treemacs-projectile.

**Comment by nixmaniack** [comment]
I tried after updating with the latest changes but it seems to not work.
Here's what I'm doing:
1. Create multiple files with `cf`
2. Switch to other window and invoke `projectile-find-file`. 

I still don't see the files I created with `cf`.

**Possible Issue:** 
I followed the [latest](https://github.com/Alexander-Miller/treemacs/blob/master/src/extra/treemacs-projectile.el#L84-L85) implementation and upon debugging, it looks like the call to `(buffer-file-name)` returns `nil` which causes the caching function [`projectile-cache-current-file`](https://github.com/bbatsov/projectile/blob/0f5018fd7e7b3a1d224d3aa96edff0b40306e79f/projectile.el#L929) to be skipped.

**Comment by Alexander-Miller** [comment]
Turns out `create-file-buffer` just creates a buffer with a fitting name, it doesn't actually open the file. Let's try again, does this version work for you?

```Elisp
(defun treemacs-projectile--add-file-to-projectile-cache (path)
  "Add created file PATH to projectile's cache."
  (let ((file-buffer (get-file-buffer path))
        (kill? nil))
    (unless file-buffer
      (setf file-buffer (find-file-noselect path)
            kill? t))
    (with-current-buffer file-buffer
      (projectile-find-file-hook-function))
    (when kill? (kill-buffer file-buffer))))
```

I cannot reproduce it either way, the created file is always found on my end. Is there anything else I need to do other than set `projectile-enable-caching` to t?

**Comment by nixmaniack** [comment]
Above code snippet works 👍.

Based on the code walkthrough, another variable that affects the codepath is `projectile-auto-update-cache` which is `t` by default which defines `Wether the cache should automatically be updated when files are opened or deleted.`

Also, if it matters, I'm using emacs head (and also use Spacemacs but results were same without that as well).

**Comment by Alexander-Miller** [comment]
> I'm not sure if there's anything in projectile which always invalidates the cache in your case.

:man_shrugging: The fix is pushed, that's the important part.

**Comment by nixmaniack** [comment]
Thanks!
