### ISSUE TITLE
Right click menu not usable in Emacs 29 context-menu-mode

### ISSUE THREAD

**Issue by Compro-Prasad** [Alexander-Miller/treemacs#909]
When `context-menu-mode` is enabled, right click doesn't work properly. This opportunity can be used to implement proper context menus per file and directory in treemacs.

**Comment by bestlem** [comment]
It is still a problem. If context-menu-mode is turned on then mouse-3 is bound in context-menu-mode-map
As this is a monor mode map this overrides the treemacs-mode-map.

**Comment by Compro-Prasad** [comment]
@Alexander-Miller `context-menu-mode` was introduced in Emacs 28.1 and I am actively using it. Whenever I interact with `treemacs` I have to disable it. I know this is not a top priority in general but I would love to use inbuilt Emacs features as much as possible.

**Comment by bestlem** [comment]
This is still an issue - I have to put the treemacs menu on mouse-2 as mouse-3 is the emacs context menu, treemacs should be using this.

**Comment by Alexander-Miller** [comment]
I'll see what I can do.

**Comment by Alexander-Miller** [comment]
Right-click menu should work now.
Let me know if anything is missing.

**Comment by bestlem** [comment]
Thanks.

Yes it is working now.

However a better but more complex fix would be to add treemacs things to context-menu but the current setup works for most cases.

Also note that for the [Mitsuharu Yamamoto](https://bitbucket.org/mituharu/) port for macOS you get error beeps as its context-menu differs - as it was written long before the GNU/Emacs version as Macs have always had context menus. The message buffer shows `mac-mouse-context-menu: Empty menu`

**Comment by Alexander-Miller** [comment]
> The message buffer shows mac-mouse-context-menu: Empty menu

I've no Mac, so I cannot add workarounds for this myself. A PR for that would be welcome of course.

**Comment by Compro-Prasad** [comment]
This isn't fixed yet. This is what I did:

1. Fired up the Emacs from latest master
2. Enabled melpa. [Ref: https://melpa.org/#/getting-started]
3. Installed treemacs
4. Enabled `context-menu-mode`
5. `M-x treemacs /`
6. Right click on any directory shows empty menu
